app = "dify-single-docker"
primary_region = "atl"

[build]
  dockerfile = "Dockerfile.flyio"

[[services]]
  internal_port = 80
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

[[mounts]]
  source = "dify_single_docker_data"
  destination = "/mnt/app"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2