[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
port = 80
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
SECRET_KEY = { default = "sk-changethissecretkey123456789012345678901234567890" }
INIT_PASSWORD = { default = "admin123456" }
PORT = { default = "80" }